name: Deploy Monorepo

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main

  # Allows manual triggering from the Actions tab
  workflow_dispatch:

# Permissions needed for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # backend-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log in to DigitalOcean Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ secrets.DOCR_REGISTRY }}
  #         username: ${{ secrets.DOCR_USERNAME }}
  #         password: ${{ secrets.DOCR_PASSWORD }}

  #     - name: Build and push Docker image
  #       run: |
  #         docker build -t ${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPOSITORY }}:latest ./backend
  #         docker push ${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPOSITORY }}:latest

  frontend-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Build static site
        run: cd frontend && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
